version: "3.7"

services:
    nats-streaming-server:
        image: nats-streaming:latest
        command: --store file --dir ./nats  --max_msgs 0 --max_bytes 256gb --debug
        ports:
            - 4222:4222
            - 8222:8222
        restart: always
        volumes:
            - ./nats :/nats

networks:
    default:
        driver: bridge
